version: '3'

services:
  customercommandside:
    build: ./customers-service/
    ports:
      - "8081:8080"
    environment:
      EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
      EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

  orderhistoryqueryside:
    build: ./orders-history-view-service/
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/customers_and_orders
      EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
      EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

  ordercommandside:
    build: ./orders-service/
    ports:
      - "8083:8080"
    depends_on:
        - customercommandside
    environment:
      CUSTOMER_SERVICE_URL: http://customercommandside:8080/customers/{customerId}
      ENDPOINTS_SENSITIVE: "false"
      EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
      EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

  mongodb:
    image: mongo:3.0.4
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "27017:27017"
