version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-examples-java-customers-and-orders
    steps:
      - checkout
      - restore_cache:
          key: eventuate-examples-java-customers-and-orders-{{ checksum "gradle.properties" }}
      - run:
          command: |
            export TERM=dumb
            cd common-contracts
            ./mvnw install
            cd ..
            ./gradlew testClasses
            ./gradlew -P eventuateDriver=local testClasses
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: eventuate-examples-java-customers-and-orders-{{ checksum "gradle.properties" }}
      - run:
          command: |
            . ./setenv-circle-ci.sh
            ./build-and-test-all-eventuate-local-mysql.sh
      - run:
          command: |
            . ./setenv-circle-ci.sh
            ./build-and-test-all-eventuate-local-postgres-polling.sh
      - run:
          command: |
            . ./setenv-circle-ci.sh
            ./build-and-test-all-eventuate-local-postgres-wal.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
